name: Build and Deploy Website via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build  

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ftp.citygirlswhowalkdelhi.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /public_html/
