name: Generate a build and create a pull request

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Create Pull Request
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build the project
        run: npm run build # The build command of your project

      - name: Push dist folder to a temporary branch
        uses: s0/git-publish-subdir-action@develop
        with:
          branch: temp-branch # Temporary branch where the dist folder will be pushed
        env:
          REPO: self
          BRANCH: temp-branch
          FOLDER: dist # This is the folder where the build files are located
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"

      - name: Wait for Git to sync
        run: sleep 10s # Ensure Git registers the push before creating a PR

      - name: Create Pull Request from temp-branch to build
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: temp-branch # Source branch for the PR (temp-branch where dist was pushed)
          base: build # Target branch for the PR (where you want to merge the build files)
          title: "Build: ${{ github.event.head_commit.message }}"
          body: "This pull request contains the latest build artifacts."
