name: Generate a build and create a pull request

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Create Pull Request
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Pull latest from main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin main

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # The build command of your project

      - name: Push to a temporary branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: temp-branch # Push to a temporary branch
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: temp-branch # The branch where the assets were pushed
          base: build # The target branch for the PR
          title: "Build: ${{ github.event.head_commit.message }}"
          body: "This pull request contains the latest build artifacts."
