name: Generate a build and push to build branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push to Build Branch
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build the project
        run: npm run build 

      - name: Push dist folder to build branch
        uses: s0/git-publish-subdir-action@develop
        with:
          branch: build
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
