name: Generate a build and create a pull request
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Create Pull Request
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install all dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update build artifacts
          title: 'Update build artifacts'
          body: |
            This PR updates the build artifacts.
            - Built with GitHub Actions
          branch: update-build-artifacts
          base: build
          delete-branch: true
