name: Generate a build and create a pull request

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Dist Files
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build the project
        run: npm run build # This command will generate the dist folder

      - name: Set up Git for pushing
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"

      - name: Checkout the build branch
        run: git checkout build

      - name: Remove existing dist files from build branch
        run: |
          git rm -r * # Remove all files in the build branch
          git clean -fd # Clean untracked files

      - name: Copy dist files to build branch
        run: |
          cp -R dist/* . # Copy dist files to the root of the build branch

      - name: Commit and push dist files
        run: |
          git add .
          git commit -m "Deploy dist files"
          git push origin build
